source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZSWRoundedImage_Example', :exclusive => true do
  pod "ZSWRoundedImage", :path => "../"
end

target 'ZSWRoundedImage_Tests', :exclusive => true do
  pod "ZSWRoundedImage", :path => "../"

  
end
